language: cpp

compiler:
  - clang
  - gcc

script: cmake . && make

os:
  - linux
  - windows

notifications:
  slack: paths2015:FypS2DzZO1DUg83AoDu9RAWq

before_install:
  - sudo apt-get install software-properties-common -qq
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -qq
  - sudo apt-get update -qq
  - sudo apt-get upgrade -qq